### ISSUE TITLE
Command line tool for clusterqueue/localqueue/workload listing and management  

### ISSUE THREAD

**Issue by mwielgus** [kubernetes-sigs/kueue#2076]
**What would you like to be added**:

A tool (for example a kubectl plugin) to perform listing and management operations on Kueue objects. 

**Why is this needed**:

Many common operations (like listing pending workloads from a particular cluster queue, draining a queue, pausing workload admission, moving workloads between queues) require advanced API knowledge and are inconvenient to execute using kubectl. 

#487 covers only listing, we need a broader tool.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mbobrovskyi** [comment]
- [ ] [kueuectl] Add validation for ClusterQueue on creating LocalQueue #2112
- [ ] [kueuectl] Allow create ClusterQueue #2113
- [ ] [kueuectl] Add list ClusterQueue command #2114
- [ ] [kueuectl] Add list LocalQueue command #2115

**Comment by alculquicondor** [comment]
/close

All tasks are completed
