### ISSUE TITLE
[Umbrella] ☂️ Requirements for release 0.2.0

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/kueue#222]
Issues that we need to complete to consider Kueue ready for the second release:

I suggest to focus only on issues related to [Productionisation](https://github.com/kubernetes-sigs/kueue/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fproductionization):
- [x] [Knobs to configure which jobs Kueue manages](https://github.com/kubernetes-sigs/kueue/issues/169) 
- [x] [More detailed pending event](https://github.com/kubernetes-sigs/kueue/issues/189)
- [x] [Handle Pod overhead added during pod admission](https://github.com/kubernetes-sigs/kueue/issues/119)
- [x] [Add "Frozen" ClusterQueue state](https://github.com/kubernetes-sigs/kueue/issues/134)
- [x] [Rename image to registry.k8s.io/kueue/kueue](https://github.com/kubernetes-sigs/kueue/issues/226)
- [x] [Manage webhook cert internally](https://github.com/kubernetes-sigs/kueue/issues/232)
- [x] [Trigger the movement of workload in ClusterQueue by ns event](https://github.com/kubernetes-sigs/kueue/issues/234)
- [x] [Add webhook for APIs defaulting and validation](https://github.com/kubernetes-sigs/kueue/issues/171)
  - #308
- [x] [Add ClusterQueue and Queue Metrics](https://github.com/kubernetes-sigs/kueue/issues/199)
  - #324
- [x] [Using the same flavors in different resources might lead to unschedulable pods](https://github.com/kubernetes-sigs/kueue/issues/167) 
- [x] [Avoid queueing workloads that don't match CQ namespaceSelector](https://github.com/kubernetes-sigs/kueue/issues/301)
- [x] [Should we use server-side apply for admission?](https://github.com/kubernetes-sigs/kueue/issues/164)
- [x] [Rename the namespaced resource "Queue" ](https://github.com/kubernetes-sigs/kueue/issues/330)
- [x] Update docs

Nice to have:
- [ ] [Add real E2E test setup and first test](https://github.com/kubernetes-sigs/kueue/issues/61)
- [ ] [Add scalability tests](https://github.com/kubernetes-sigs/kueue/issues/45)

**Comment by ahg-g** [comment]
Our backlog of features is listed below, but I think we shouldn't add any more features before closing our backlog of productionization/hardening related issues:
- [Support Spark jobs specifically and dynamically sized jobs](https://github.com/kubernetes-sigs/kueue/issues/77)
- [Support kubeflow's MPIJob](https://github.com/kubernetes-sigs/kueue/issues/65)
- [Replace borrowing ceiling with weights](https://github.com/kubernetes-sigs/kueue/issues/62)
- [Budgets](https://github.com/kubernetes-sigs/kueue/issues/28)
- [Workload preemption](https://github.com/kubernetes-sigs/kueue/issues/83)
- [Simple Framework to support different queuing policies](https://github.com/kubernetes-sigs/kueue/issues/10)
- [Hierarchical ClusterQueues](https://github.com/kubernetes-sigs/kueue/issues/79)
- [Include ClusterQueue depth in Workload status](https://github.com/kubernetes-sigs/kueue/issues/168)


@alculquicondor @denkensk @ArangoGutierrez @kerthcet what do you think?

**Comment by kerthcet** [comment]
Glad to see a backlog here, do we have a rough deadline?

**Comment by denkensk** [comment]
> Our backlog of features is listed below, but I think we shouldn't add any more features before closing our backlog of productionization/hardening related issues.

sgtm.

**Comment by ArangoGutierrez** [comment]
lgtm

**Comment by alculquicondor** [comment]
#232 to simplify deployment of webhooks

**Comment by ahg-g** [comment]
Should we set a deadline as @kerthcet suggested? Perhaps after KubeCon?

**Comment by alculquicondor** [comment]
I think we still have a lot to solve, so I wouldn't bet on a release within a week of Kubecon. Maybe June 15th for the batch live panel? https://opensourcelive.withgoogle.com/learn-kubernetes

**Comment by ArangoGutierrez** [comment]
226 is closed now :)

**Comment by kerthcet** [comment]
Maybe we can release regularly to avoid similar discussion later. Features are always there.

**Comment by alculquicondor** [comment]
FYI
@ahg-g and I will be in kubecon next week (May 16th), so we might have limited time to approve PRs.
The week after, we are both out on vacation (May 23th).
I'll be back in May 30th.

**Comment by denkensk** [comment]
@ahg-g  @alculquicondor  Have a nice vacation! 
I could probably spend more time fixing some urgent issues and reviewing code.

**Comment by kerthcet** [comment]
Have a wonderful speech 🚀, and I'll help on reviewing the same time.

**Comment by kerthcet** [comment]
> consider adding #103 to this release as well

I'm already in settling the deletion part of the work.

**Comment by kerthcet** [comment]
What is left for v0.2.0, it seems the necessary ones are all finished.

**Comment by alculquicondor** [comment]
#341, update API version to v1alpha2, and update documentation

**Comment by alculquicondor** [comment]
Started the release checklist in #352
