### ISSUE TITLE
☂️ Requirements for release 0.3

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#360]
```[tasklist]
### Tasks
- [x] https://github.com/kubernetes-sigs/kueue/issues/45
- [x] https://github.com/kubernetes-sigs/kueue/issues/83
- [x] https://github.com/kubernetes-sigs/kueue/issues/425
- [ ] https://github.com/kubernetes-sigs/kueue/issues/349
- [ ] https://github.com/kubernetes-sigs/kueue/issues/23
```

Nice to have:

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/kueue/issues/312
- [x] https://github.com/kubernetes-sigs/kueue/issues/61
- [x] https://github.com/kubernetes-sigs/kueue/issues/45
- [ ] https://github.com/kubernetes-sigs/kueue/issues/541
```

I open the floor for further suggestions, but I think those two high level items are big enough for a release.

**Comment by alculquicondor** [comment]
cc @ahg-g @kerthcet @denkensk @ArangoGutierrez

**Comment by ahg-g** [comment]
Yes, that should be enough material improvements for a release.

**Comment by kerthcet** [comment]
Maybe also add e2e test https://github.com/kubernetes-sigs/kueue/issues/61

**Comment by ahg-g** [comment]
we may also want to consider https://github.com/kubernetes-sigs/kueue/issues/312 because it can help with reducing chances of preemption.

**Comment by alculquicondor** [comment]
Added #245 (as bugfix) and #349.

**Comment by alculquicondor** [comment]
/close

Thank you all for contributing!
