### ISSUE TITLE
[Umbrella] ☂️ Requirements for release 0.1.0

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#63]
Deadline: May 16th Kubecon EU

Issues that we need to complete to consider kueue ready for a first release:

- [x] Match workload affinities with flavors #3
- [x] Single heap per Capacity #87 
- [x] Consistent flavors in a cohort #59
- [x] Queue status #5
- [x] Capacity status #7 
- [x] Event for unschedulable workloads #91 
- [x] Capacity namespace selector #4
- [x] Efficient requeuing #8 
- [x] User guide #64
- [x] Publish image #52

Nice to have:

- [ ] Add borrowing weight #62
- [ ] E2E test #61
- [ ] Use kueue.sigs.k8s.io API group #23
- [ ] Support for one custom job #65

**Comment by alculquicondor** [comment]
cc @ahg-g @ArangoGutierrez @denkensk thoughts? Did I miss something?

**Comment by ArangoGutierrez** [comment]
Ohhhh that smell of a new release in the air.... uh lala

**Comment by denkensk** [comment]
User guide is also needed.

**Comment by ArangoGutierrez** [comment]
something we can quickly implement as well could be github-pages for small documentation? (I can volunteer have done that for other sigs)

**Comment by denkensk** [comment]
#14 Is there any progress on this？ @ArangoGutierrez

**Comment by ArangoGutierrez** [comment]
we agree to wait for klog/v3 no? 

```
But this is changing soon https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging

In the meantime, if we stick with logr for now, I think it will be easier to switch to klog (v3?) once it supports contextual logging.
```

**Comment by ArangoGutierrez** [comment]
I would add https://github.com/kubernetes-sigs/kueue/issues/52 to that checklist

**Comment by ahg-g** [comment]
I don't think we should block the first release on https://github.com/kubernetes-sigs/kueue/issues/62, ceiling is workable for a 0.0.1 version .

**Comment by ArangoGutierrez** [comment]
can we set KubeCon EU as dead line for this? would be a nice thing to achieve

**Comment by ahg-g** [comment]
Yeah, I submitted a proposal to present it at KubeCon the general event, but will also be discussing it in the colo event.

**Comment by alculquicondor** [comment]
I think we should be able to have something sooner. But kubecon EU is a nice hard deadline :) Added to the description.

> I don't think we should block the first release on #62, ceiling is workable for a 0.0.1 version .

I think it is indeed usable, but migrating to weights from the first version will avoid one breaking change. Sure... they are alpha APIs, but if we can avoid it, it would be great. Moved to nice-to-have.

**Comment by ArangoGutierrez** [comment]
@alculquicondor can you pin this? so is easier to find

**Comment by ahg-g** [comment]
I think we need to add https://github.com/kubernetes-sigs/kueue/issues/4 to the list, I will do that.

**Comment by ahg-g** [comment]
also https://github.com/kubernetes-sigs/kueue/issues/91

**Comment by ArangoGutierrez** [comment]
check mark `Publish image https://github.com/kubernetes-sigs/kueue/issues/52`

**Comment by ArangoGutierrez** [comment]
Check `Single heap per Capacity https://github.com/kubernetes-sigs/kueue/issues/87` ✅

**Comment by ArangoGutierrez** [comment]
we have an image!!!
`gcr.io/k8s-staging-kueue/kueue:devel`

```bash
[eduardo@fedora-workstation kueue]$ skopeo list-tags docker://gcr.io/k8s-staging-kueue/kueue
{
    "Repository": "gcr.io/k8s-staging-kueue/kueue",
    "Tags": [
        "devel"
    ]
}
```

**Comment by ArangoGutierrez** [comment]
CHeckMark -> `Queue status https://github.com/kubernetes-sigs/kueue/issues/5`

**Comment by ArangoGutierrez** [comment]
Checkmark Event for unschedulable workloads https://github.com/kubernetes-sigs/kueue/issues/91

**Comment by ArangoGutierrez** [comment]
checkmark `User guide https://github.com/kubernetes-sigs/kueue/issues/64`

**Comment by alculquicondor** [comment]
@ahg-g @denkensk @ArangoGutierrez PTAL at the draft for release notes in the issue description.

**Comment by ArangoGutierrez** [comment]
can we use https://github.com/kubernetes-sigs/kueue/blob/main/.github/ISSUE_TEMPLATE/NEW_RELEASE.md ?

**Comment by alculquicondor** [comment]
Opened #197

**Comment by ahg-g** [comment]
A couple of other renames we should do: 
1. cq.requestableResources -> resources
2. cq.flavor.resourceFlavor -> cq.flavor.name

**Comment by ahg-g** [comment]
Before the first release we need to ignore jobs with queue name not set; this is important so users are not surprised that their existing running jobs get suspended when they first try Kueue.

We will add a flag to ComponentConfig to disable this behavior, and a namespace selector to select which namespaces the job-controller will take over. We can do that in the next release.

**Comment by alculquicondor** [comment]
sgtm, can you open an issue and/or PR?

**Comment by alculquicondor** [comment]
> A couple of other renames we should do:
> 
> 1. cq.requestableResources -> resources
> 2. cq.flavor.resourceFlavor -> cq.flavor.name

I'm in favor of 2, but not 1.

**Comment by ahg-g** [comment]
https://github.com/kubernetes-sigs/kueue/pull/205 disables reconciling jobs with no queue name set.

**Comment by ahg-g** [comment]
and https://github.com/kubernetes-sigs/kueue/pull/206 for renaming requestableResources in the api.

**Comment by ahg-g** [comment]
and https://github.com/kubernetes-sigs/kueue/pull/207 for component config

**Comment by alculquicondor** [comment]
All items are complete. We probably leave the nice-to-have issues for the next release.

/close
